### ISSUE TITLE
Transfer ownership to neotest org

### ISSUE THREAD

**Issue by akinsho** [nvim-neotest/neotest-go#2]
Hi @rcarriga,

Now you've created the neotest organization, I'd be happy to move this repo under that umbrella, although I'd like to maintain access, so I can keep iterating on it. Not sure how privileges work with GitHub orgs, but I'd only need/want push access to this repo.

**Comment by rcarriga** [comment]
OK so checked this out and I can give you full read write for the repo, no problem. You have to transfer ownership of the repo to nvim-neotest org (can do this in settings, bottom of the initial page in the "Danger Zone") and then I can assign you the permissions

**Comment by rcarriga** [comment]
I had to add you as a member of the org first woops, should be able to transfer now!

**Comment by akinsho** [comment]
Done 👍🏿, I'll update the README to be more generic.

**Comment by rcarriga** [comment]
Cool, don't forget to update the install instructions too :smile:
