### ISSUE TITLE
Test-Table feature only works partially

### ISSUE THREAD

**Issue by marcomayer** [nvim-neotest/neotest-go#29]
Using the following test example:

`func TestSomeTest(t *testing.T) {
	tt := []struct {
		name   string
		method string
		url    string
		apiKey string
		status int
	}{
		{name: "AccessDenied1", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied2", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied3", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied4", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied5", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied6", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
	}

	for _, tc := range tt {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			fmt.Println(tc.name, tc.method, tc.url, tc.apiKey, tc.status)
		})
	}
}
`
And running it using `lua require('neotest').run.run()` It will run the whole test but only show checkmarks for some of the tests (seems random which ones it picks). Also looking at the neotest-summary I also just see 2-3 of the tests:
![image](https://user-images.githubusercontent.com/10881376/206424778-cc08489f-186f-493f-874c-5e584e5033ad.png)

I'm using the latest neovim stable 0.8.1 and the latest golang 0.19.4

**Comment by akinsho** [comment]
Please feel free to open a PR to help fix this. This plugin has no official maintainer and is entirely contributed by the community.

**Comment by marcomayer** [comment]
Okay, thanks. I've spent half an hour trying to understand what's going on there but as treesitter queries are new for me, I'd need to spend much more time to get a grasp on this. Till then I'll turn test_tables off for now.

**Comment by marcomayer** [comment]
Unfortunately, there's still an issue starting at more than 9 tests, using this example:
```
func TestSomeTest(t *testing.T) {
	tt := []struct {
		name   string
		method string
		url    string
		apiKey string
		status int
	}{
		{name: "AccessDenied1", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied2", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied3", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied4", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied5", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied6", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},

		{name: "AccessDenied7", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied8", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied9", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
		{name: "AccessDenied10", method: http.MethodGet, url: "/api/nothing", apiKey: "lalala", status: http.StatusForbidden},
	}
	for _, tc := range tt {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			fmt.Println(tc.name, tc.method, tc.url, tc.apiKey, tc.status)
		})
	}
}

```

"AccessDenied1" falls out of the results. @sergii4 @akinsho should we reopen this?

**Comment by sergii4** [comment]
@marcomayer seems so. Nice catch. I can take a look later

**Comment by sergii4** [comment]
Probably it is a `nvim-treestitter` issue. I run same query on the online tree-sitter playground and using tree-sittier-go locally and all is works perfectly.
This issue only reproduces in nvim environment
I have opened a [bug](https://github.com/nvim-treesitter/nvim-treesitter/issues/3993) on nvim-treesitter repo.

**Comment by sergii4** [comment]
@akinsho @marcomayer I pulled out last version of nvim that includes [fix](https://github.com/neovim/neovim/issues/22055). Everything is working for me now.

Could you please check it on your side?

<img width="1136" alt="Screenshot 2023-03-06 at 12 46 47" src="https://user-images.githubusercontent.com/13333099/223684756-922a898a-1254-45c5-abca-e9c1e5aa5506.png">

**Comment by marcomayer** [comment]
@sergii4 thanks a lot, yes this fixes it!

**Comment by sergii4** [comment]
@marcomayer thanks for drawing attention to it!
