### ISSUE TITLE
Failed to run unit test function

### ISSUE THREAD

**Issue by tubzby** [nvim-neotest/neotest-go#38]
I have a simple Golang project and a couple of lines of unit test function. When I run: lua require("neotest").run.run(), it fails with:

``` console
directory ../../local/uavm outside main module or its selected dependencies.
```

I have followed the installation instructions of neotest and neotest-go.

**Comment by sergii4** [comment]
Hi @tubzby, issue caused by Go requirements itself itself. You have to run tests from module root directory

**Comment by tubzby** [comment]
Seems that it's not working properly inside a *soft link* directory, it works after I cd inside the link destination directory.

**Comment by sergii4** [comment]
I mean it is how underlying tool, `go test`, works. You can check it by yourself running `go test {your_dir}` and compare results with `neotest-go`.
I don't see what can we do on an adapter side

**Comment by tubzby** [comment]
@sergii4 got it!

**Comment by sergii4** [comment]
@tubzby I reopen the issue, I assume we have to resolve it to make it easies to use for broader circle of people. I am working on it
