### ISSUE TITLE
Neotest Summary window is showing incorrect status

### ISSUE THREAD

**Issue by tfrs1** [nvim-neotest/neotest-go#45]
As in the title, the `neotest.summary` window is showing incorrect status at at least the file level.

<img width="300" alt="Screenshot 2023-05-02 at 18 34 54" src="https://user-images.githubusercontent.com/686255/235730441-d5042f4c-6538-4a90-9553-ccce66465040.png">

From what I've been able to gather, this is related to changes in https://github.com/nvim-neotest/neotest-go/pull/39, more specifically because of [hard-coding the result status to `"failed"` on all file nodes](https://github.com/nvim-neotest/neotest-go/pull/39/files#diff-ba39acc61170d012d9fe7694e11f1e9c7060a687fda264dec455706a38da4a8aR203). I understand that neotest is supposed to determine the status of the file node from the leaves automatically. I'm tagging you @sergii4 because you are the author.

**Comment by sergii4** [comment]
Hi @tfrs1, could you please update. I believe the issue was fixed in #44

**Comment by tfrs1** [comment]
You're right. Sorry for the false alarm.
