### ISSUE TITLE
QUESTION: run tests for entire project?

### ISSUE THREAD

**Issue by hahuang65** [nvim-neotest/neotest-go#5]
Just wondering if there was a way to run the entire project?

I've tried `require('neotest').run.run(vim.fn.getcwd())` as well as `require('neotest').run.run('./...')` but neither worked.
Wondering if I'm just doing it wrong, or should I fork this and try to implement support for it?

**Comment by akinsho** [comment]
@hahuang65 was about to say that I have no idea but found a bug when I was just cross checking where every path passed in was being truncated to the one above which is needed for file tests but breaks directory tests. This should now work with `require('neotest').run.run(vim.fn.getcwd())`

**Comment by hahuang65** [comment]
awesome, thank you so much!!
