### ISSUE TITLE
'No tests found' using minimal config

### ISSUE THREAD

**Issue by pczora** [nvim-neotest/neotest-go#51]
**Context**
With my default config, I do not have problems running any tests, however, diagnostics are not set. If I can manage to reproduce this issue with a minimal config, I'll create another issue. 
_To debug this issue, I want to run neotest-go with a minimal config._

**Neovim Version**
I am running Neovim on macOS; `nvim --version` output:

```
NVIM v0.10.0-dev-1390+g0451391ec-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-0451391/share/nvim"

Run :checkhealth for more info

```

**Minimal config**
This is the config I am using:
```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))
vim.opt.termguicolors = true

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end
local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  use("wbthomason/packer.nvim")
  use({
    "nvim-neotest/neotest",
    requires = {
    "nvim-lua/plenary.nvim",
    "nvim-treesitter/nvim-treesitter",
    "antoinemadec/FixCursorHold.nvim",
    "nvim-neotest/neotest-go",
    -- Your other test adapters here
    },
    config = function()
      -- get neotest namespace (api call creates or returns namespace)
      local neotest_ns = vim.api.nvim_create_namespace("neotest")
      vim.diagnostic.config({
        virtual_text = {
          format = function(diagnostic)
            local message =
              diagnostic.message:gsub("\n", " "):gsub("\t", " "):gsub("%s+", " "):gsub("^%s+", "")
            return message
          end,
        },
      }, neotest_ns)
      require("neotest").setup({
        -- your neotest config here
        adapters = {
          require("neotest-go"),
        },
      })
    end,
  })
  if install_plugins then
    packer.sync()
  end
end)

vim.cmd([[
command! NeotestSummary lua require("neotest").summary.toggle()
command! NeotestFile lua require("neotest").run.run(vim.fn.expand("%"))
command! Neotest lua require("neotest").run.run(vim.fn.getcwd())
command! NeotestNearest lua require("neotest").run.run()
command! NeotestDebug lua require("neotest").run.run({ strategy = "dap" })
command! NeotestAttach lua require("neotest").run.attach()
command! NeotestOutput lua require("neotest").output.open()
]])
```

If I try to run the tests in this file:

```go
package greetings

import (
	"regexp"
	"testing"
)

func TestFail(t *testing.T) {
	t.Error("Fail :(")
}

// TestHelloName calls greetings.Hello with a name, checking
// for a valid return value.
func TestHelloName(t *testing.T) {
	name := "Gladys"
	want := regexp.MustCompile(`\b` + name + `\b`)
	msg, err := Hello("Gladys")
	if !want.MatchString(msg) || err != nil {
		t.Fatalf(`Hello("Gladys") = %q, %v, want match for %#q, nil`, msg, err, want)
	}
}

// TestHelloEmpty calls greetings.Hello with an empty string,
// checking for an error.
func TestHelloEmpty(t *testing.T) {
	msg, err := Hello("")
	if msg != "" || err == nil {
		t.Fatalf(`Hello("") = %q, %v, want "", error`, msg, err)
	}
}
```

I only see the message 'No tests found'.

The logs only contain this:

```
INFO | 2023-05-18T14:30:20Z+0200 | ...hare/nvim/plugged/neotest/lua/neotest/lib/subprocess.lua:83 | CHILD | Connected to parent instance
INFO | 2023-05-18T14:33:07Z+0200 | ...l/share/nvim/plugged/neotest/lua/neotest/config/init.lua:305 | Configuration complete
DEBUG | 2023-05-18T14:33:07Z+0200 | ...l/share/nvim/plugged/neotest/lua/neotest/config/init.lua:306 | User config {
  adapters = { {
      _generate_position_id = <function 1>,
      build_spec = <function 2>,
      discover_positions = <function 3>,
      is_test_file = <function 4>,
      name = "neotest-go",
      prepare_results = <function 5>,
      results = <function 6>,
      root = <function 7>,
      <metatable> = {
        __call = <function 8>
      }
    } },
  benchmark = {
    enabled = true
  },
  consumers = {},
  default_strategy = "integrated",
  diagnostic = {
    enabled = true,
    severity = 1
  },
  discovery = {
    concurrent = 16,
    enabled = true
  },
  floating = {
    border = "rounded",
    max_height = 0.6,
    max_width = 0.6,
    options = {}
  },
  highlights = {
    adapter_name = "NeotestAdapterName",
    border = "NeotestBorder",
    dir = "NeotestDir",
    expand_marker = "NeotestExpandMarker",
    failed = "NeotestFailed",
    file = "NeotestFile",
    focused = "NeotestFocused",
    indent = "NeotestIndent",
    marked = "NeotestMarked",
    namespace = "NeotestNamespace",
    passed = "NeotestPassed",
    running = "NeotestRunning",
    select_win = "NeotestWinSelect",
    skipped = "NeotestSkipped",
    target = "NeotestTarget",
    test = "NeotestTest",
    unknown = "NeotestUnknown"
  },
  icons = {
    child_indent = "│",
    child_prefix = "├",
    collapsed = "─",
    expanded = "╮",
    failed = "",
    final_child_indent = " ",
    final_child_prefix = "╰",
    non_collapsible = "─",
    passed = "",
    running = "",
    running_animated = { "/", "|", "\\", "-", "/", "|", "\\", "-" },
    skipped = "",
    unknown = ""
  },
  jump = {
    enabled = true
  },
  log_level = 1,
  output = {
    enabled = true,
    open_on_run = "short"
  },
  output_panel = {
    enabled = true,
    open = "botright split | resize 15"
  },
  projects = {
    <metatable> = {
      __index = <function 9>
    }
  },
  quickfix = {
    enabled = false,
    open = true
  },
  run = {
    enabled = true
  },
  running = {
    concurrent = true
  },
  state = {
    enabled = false
  },
  status = {
    enabled = false,
    signs = true,
    virtual_text = false
  },
  strategies = {
    integrated = {
      height = 40,
      width = 120
    }
  },
  summary = {
    animated = true,
    enabled = false,
    expand_errors = true,
    follow = true,
    mappings = {
      attach = "a",
      clear_marked = "M",
      clear_target = "T",
      debug = "d",
      debug_marked = "D",
      expand = { "<CR>", "<2-LeftMouse>" },
      expand_all = "e",
      jumpto = "i",
      mark = "m",
      next_failed = "J",
      output = "o",
      prev_failed = "K",
      run = "r",
      run_marked = "R",
      short = "O",
      stop = "u",
      target = "t"
    },
    open = "botright vsplit | vertical resize 50"
  }
}
```
So, no call to `go test`

**Comment by msvitok77** [comment]
I have the same problem. I have tested this with nvim v0.9.1 and v0.9.0 as I thought they have somehow changed the API. However none of them worked. This is basically a blocker.

**Comment by testinfected** [comment]
Same here too

**Comment by Zeioth** [comment]
Same here. I have a simple hello world project initialized with `go init main`, and the test passes correctly on the terminal doing `main_test.go`, but neotest show `No tests found`.

I have added the neotest-go adapter and dependency to neotest.
![screenshot_2023-08-12_22-49-54_827049936](https://github.com/nvim-neotest/neotest-go/assets/3357792/f229eb7d-8463-455c-8a2e-27851a54c041)
![screenshot_2023-08-12_22-50-08_481558813](https://github.com/nvim-neotest/neotest-go/assets/3357792/dd5d86ba-bb7d-49e1-9a44-7abbf948b997)

**Comment by sergii4** [comment]
Will take a look soon

**Comment by sergii4** [comment]
Was able to reproduce. Take a look further today/tomorrow

**Comment by sergii4** [comment]
Actually, @pczora , it perfectly works for me. 

I have created new droplet on Digital Ocean:
>1 GB Memory / 25 GB Disk / LON1 - Ubuntu 22.04 (LTS) x64
I called go file that you provided `main_test.go` and changed package to `main`.

I put your config to lua/init.lua and run:
```
nvim -u lua/init.lua main_test.go
```
then
```
:lua require("neotest").run.run()
```
My ` nvim --version`:
```
NVIM v0.10.0-dev-530+g8376e8700

Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/build/nvim/parts/nvim/build/.deps/usr/include/luajit-2.1 -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

**Comment by Zeioth** [comment]
Ok it works now on my end now: It seems that in order to be detected as test by neotest-go, the test must follow the naming convention filename_test.go.

Probably one can override this as:
```
require("neotest").setup({
  adapters = {
    require("neotest-go")({
        -- NB: This function is called a lot so don't perform any heavy tasks within it.
        is_test_file = function(file_path)
          ...
        end,
        
    })
  }
})
```

Or at least it is possible on neotest-python.

**Comment by msvitok77** [comment]
For me still no luck. I have used the @pczora config:
`-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))
vim.opt.termguicolors = true

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end
local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  use("wbthomason/packer.nvim")
  use({
    "nvim-neotest/neotest",
    requires = {
    "nvim-lua/plenary.nvim",
    "nvim-treesitter/nvim-treesitter",
    "antoinemadec/FixCursorHold.nvim",
    "nvim-neotest/neotest-go",
    -- Your other test adapters here
    },
    config = function()
      -- get neotest namespace (api call creates or returns namespace)
      local neotest_ns = vim.api.nvim_create_namespace("neotest")
      vim.diagnostic.config({
        virtual_text = {
          format = function(diagnostic)
            local message =
              diagnostic.message:gsub("\n", " "):gsub("\t", " "):gsub("%s+", " "):gsub("^%s+", "")
            return message
          end,
        },
      }, neotest_ns)
      require("neotest").setup({
        -- your neotest config here
        adapters = {
          require("neotest-go"),
        },
      })
    end,
  })
  if install_plugins then
    packer.sync()
  end
end)

vim.cmd([[
command! NeotestSummary lua require("neotest").summary.toggle()
command! NeotestFile lua require("neotest").run.run(vim.fn.expand("%"))
command! Neotest lua require("neotest").run.run(vim.fn.getcwd())
command! NeotestNearest lua require("neotest").run.run()
command! NeotestDebug lua require("neotest").run.run({ strategy = "dap" })
command! NeotestAttach lua require("neotest").run.attach()
command! NeotestOutput lua require("neotest").output.open()
]])`

placed it to `~/.config/init.lua` as usual.

Then used this test file:
`package main

import "testing"

func Test_a(t *testing.T) {
	tests := []struct {
		name    string
		want    int
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, err := a()
			if (err != nil) != tt.wantErr {
				t.Errorf("a() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("a() = %v, want %v", got, tt.want)
			}
		})
	}
}

func Test_main(t *testing.T) {
	tests := []struct {
		name string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			main()
		})
	}
}`

Then run: `:NeotestNearest<cr>` ... nothing happens, run it again, got `No tests found` in the status line.

**neovim version:** 
`NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info`

**lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Comment by jan-xyz** [comment]
I'm also on Nvim 0.9.1 and it's broken. I noticed that @sergii4 you are on 0.10.0 is it maybe some treesitter thing that only works on the nightly?

**Comment by msvitok77** [comment]
> I'm also on Nvim 0.9.1 and it's broken. I noticed that @sergii4 you are on 0.10.0 is it maybe some treesitter thing that only works on the nightly?

Yes that was my idea as well as treesitter API is changing a lot. That was the reason I tried both **0.9.0** and **0.9.1**, but none of them worked.

**Comment by sergii4** [comment]
@Zeioth what the point in overriding that function? There is [name convention](https://pkg.go.dev/testing) for test files in Go and we must follow it:
> To write a new test suite, create a file that contains the TestXxx functions as described here, and give that file a name ending in "_test.go". The file will be excluded from regular package builds but will be included when the "go test" command is run.

**Comment by sergii4** [comment]
Hi @jan-xyz, there were some [breaking changes](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293) introduced, however it doesn't related to `neotest`/`neotest-go`. Probably an issue need to be opened for `nvim-treesotter`.

It doesn't on my machine as well:
```
$ uname -a

Darwin Sergiis-MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
```

**Comment by msvitok77** [comment]
> @msvitok77 what's the name of test file you run test against?

example_test.go... it's a standard golang convention.

**Comment by sergii4** [comment]
@msvitok77 Thanks! I am asking because not everybody follows that convention. 

I assume minimal config is not enough to blame neotest/neotest-go. We need some minimal environment. I assume I can spend some time later on playing with some basic Ubuntu image.

But my experiment with Digital Ocean image shows that neotest/neotest-go are doing just fine.

**Comment by msvitok77** [comment]
> @msvitok77 Thanks! I am asking because not everybody follows that convention.
> 
> I assume minimal config is not enough to blame neotest/neotest-go. We need some minimal environment. I assume I can spend some time later on playing with some basic Ubuntu image.
> 
> But my experiment with Digital Ocean image shows that neotest/neotest-go are doing just fine.

Thanks @sergii4. Did you try to use the v0.9.1 (which is the latest stable version of neovim)?

**Comment by msvitok77** [comment]
> @msvitok77 I didn't. As you can see I tried:
> 
> ```
> NVIM v0.10.0-dev-530+g8376e8700
> ```

Yes I read about that. But IMHO the plugin should work with the latest stable version as well. What do you think?

**Comment by sergii4** [comment]
@msvitok77 It indicates that the latest nightly can have something that latest stable build doesn't have if neotest/netest-go version the same. There is a high probability that problem is beyond neotest/netest-go but in neovim/tree-sitter for example

**Comment by sergii4** [comment]
>Well yes that's possible. But if I recall correctly, I was using neotest-go with the previous versions of neovim successfully. What I can do is to use the v0.8.3 or v0.8.2 which for sure worked with neotest-go

But if it works on v0.8.3 or v0.8.2, doesn't work on v0.9.1, works again v0.10.0-dev-530+g8376e8700 why is neotest-go to blame if haven't changed? 🙂 It doesn't seem logical to me 🤷‍♂️

**Comment by msvitok77** [comment]
> > Well yes that's possible. But if I recall correctly, I was using neotest-go with the previous versions of neovim successfully. What I can do is to use the v0.8.3 or v0.8.2 which for sure worked with neotest-go
> 
> But if it works on v0.8.3 or v0.8.2, doesn't work on v0.9.1, works again v0.10.0-dev-530+g8376e8700 why is neotest-go to blame if it haven't changed? slightly_smiling_face It doesn't seem logical to me man_shrugging

I'm not blaming anyone for the moment :-), just trying to find the problem. I was trying to write my own golang test plugin, but once I noticed how often the treesitter API changes, I gave up on this. So I can try this with older versions and will let you know.

**Comment by tkg-codes** [comment]
I'm having the same issue with `v0.10.0-beta` when using a very simple test setup with `main.go` and `main_test.go`. Funnily enough, a much more complicated setup that I used on my work laptop worked fine as far as Friday. I'll check in the morning whether it still works.

**Comment by msvitok77** [comment]
@sergii4 I can confirm that with versions: v0.8.3 and v0.8.2 it works well. So there were definitely some breaking changes in v0.9.0 and v0.9.1 ...

**Comment by brianfiszman** [comment]
Having the same issue... still no solution??? I'm using v0.9.1

**Comment by brianfiszman** [comment]
> > Was experiencing the same problem running NVIM v0.10.0-dev-1031+gc431d820e
> > [...]
> > Explicitly uninstalling then installing the go parser had solved the issue tho!
> > ```
> > 
> > TSUninstall go
> > 
> > TSInstall go
> > ```
> 
> Wow! Thank you! This solved it for me also on 0.9!



> Was experiencing the same problem running NVIM v0.10.0-dev-1031+gc431d820e
> 
> * observed that test files were visible but individual tests weren't `require('neotest').summary.open()`
> * likewise treesitter playground was blank
> * running `TSUpdate go` had no effect on either of the above
> 
> Explicitly uninstalling then installing the go parser had solved the issue tho!
> 
> ```
> TSUninstall go
> TSInstall go
> ```

![image](https://github.com/nvim-neotest/neotest-go/assets/13773140/07a804d5-6219-49b1-8f3f-98c1f3eecfc6)
happens to me when i use the test_table feature and I kinda need that feature

**Comment by vitorf7** [comment]
> > > Was experiencing the same problem running NVIM v0.10.0-dev-1031+gc431d820e
> > > [...]
> > > Explicitly uninstalling then installing the go parser had solved the issue tho!
> > > ```
> > > 
> > > TSUninstall go
> > > 
> > > TSInstall go
> > > ```
> > 
> > Wow! Thank you! This solved it for me also on 0.9!
> 
> 
> 
> > Was experiencing the same problem running NVIM v0.10.0-dev-1031+gc431d820e
> > 
> > * observed that test files were visible but individual tests weren't `require('neotest').summary.open()`
> > * likewise treesitter playground was blank
> > * running `TSUpdate go` had no effect on either of the above
> > 
> > Explicitly uninstalling then installing the go parser had solved the issue tho!
> > 
> > ```
> > TSUninstall go
> > TSInstall go
> > ```
> 
> ![image](https://github.com/nvim-neotest/neotest-go/assets/13773140/07a804d5-6219-49b1-8f3f-98c1f3eecfc6)
> **Happens** to me when i use the test_table feature and I kinda need that feature
> 
> 
> To be more clear, when I run NeotestFile I get Tests Not Found
> 
> ![image](https://github.com/nvim-neotest/neotest-go/assets/13773140/e5919697-368d-4c1d-98ef-24320261a9ad)
> 
> 

Yes same is happening to me when I turn on the test table feature it tells me no tests found in the whole file but without the test table it will run the tests and has the sign that it passed next to the function.

**Comment by vitorf7** [comment]
It seems to be working now after I updated neotest, neotest-go and neovim HEAD.
I currently have the following versions in my `lazy-lock.json` :
```json
  "neotest": { "branch": "master", "commit": "1e67a504d03def3a6a1125d934cb511680f72555" },
  "neotest-go": { "branch": "main", "commit": "1a15e1136db43775214a3e7a598f8930c29c94b7" },
```
And this is what `nvim --version` returns:
```bash
NVIM v0.10.0-dev-1080+g676e1d490
Build type: RelWithDebInfo
LuaJIT 2.1.1694316387
Run "nvim -V1 -v" for more info
```
![Screenshot 2023-09-11 at 15 46 57](https://github.com/nvim-neotest/neotest-go/assets/469102/a8628a04-345d-4d14-9ad4-3548f1381f00)

**Comment by sergii4** [comment]
There was a problem with our queries after parsers update for nvim-treesitter. I merged fix yesterday(#60)

**Comment by vitorf7** [comment]
> merged

Amazing work and thanks for the response. So nice to see each individual case with the tick when it passes.
Again thanks for the hard work

**Comment by sergii4** [comment]
Thanks a lot, @vitorf7! It was difficult to understand on what side a problem since there were no breaking changes in neotest-go itself. Even after realising that parsers were updated and we have to align our queries it wasn't so straightforward to find a bug in query that just worked well before. 

I am just curious if issue is still relevant or we can close it? @pczora

**Comment by brianfiszman** [comment]
> Thanks a lot, @vitorf7! It was difficult to understand on what side a problem since there were no breaking changes in neotest-go itself. Even after realising that parsers were updated and we have to align our queries it wasn't so straightforward to find a bug in query that just worked well before.
> 
> I am just curious if issue is still relevant or we can close it? @pczora

Hey @sergii4 I'm getting false positives here, the tests are showing no errors even when they should...
![image](https://github.com/nvim-neotest/neotest-go/assets/13773140/cb016f64-914a-407e-9f38-095683c069b5)
Could this be because I'm using COC instead of native LSP??? Maybe treesitter...
I'm running the tests with `lua require("neotest").run.run(vim.fn.expand("%"))` 

This is my config:
```lua
local neotest = require("neotest")
local neotest_ns = vim.api.nvim_create_namespace("neotest")

require("neodev").setup({
  library = { plugins = { "neotest" }, types = true },
})


vim.diagnostic.config({
  virtual_text = {
    format = function(diagnostic)
      local message =
          diagnostic.message:gsub("\n", " "):gsub("\t", " "):gsub("%s+", " "):gsub("^%s+", "")
      return message
    end,
  },
}, neotest_ns)


neotest.setup({
  adapters = {
    require('neotest-jest')({
      jestCommand = "npm test --",
      jestConfigFile = "custom.jest.config.ts",
      env = { CI = true },
      cwd = function(path)
        return vim.fn.getcwd()
      end,
    }),
    require("neotest-go")({
      experimental = {
        test_table = true,
      },
      args = { "-count=1", "-timeout=60s" }
    }),
    require("neotest-plenary")
  },
  consumers = {
    overseer = require("neotest.consumers.overseer"),
  },
  overseer = {
    enabled = true,
    -- When this is true (the default), it will replace all neotest.run.* commands
    force_default = false,
  },
  status = { virtual_text = true },
  output = { open_on_run = true },
})



vim.cmd([[
command! NeotestSummary lua require("neotest").summary.toggle()
command! NeotestFile lua require("neotest").run.run(vim.fn.expand("%"))
command! Neotest lua require("neotest").run.run(vim.fn.getcwd())
command! NeotestNearest lua require("neotest").run.run()
command! NeotestDebug lua require("neotest").run.run({ strategy = "dap" })
command! NeotestAttach lua require("neotest").run.attach()
command! NeotestOutput lua require("neotest").output.open()
]])

vim.keymap.set('n', '<space>t', vim.cmd.NeotestFile)
```

**Comment by sergii4** [comment]
Hi @brianfiszman, I need to take a look closer. It will take some time.

**Comment by pczora** [comment]
> [...]
> I am just curious if issue is still relevant or we can close it? @pczora

I just checked the exact some config which I provided in my original post; only with a more up to date nvim version:

```
NVIM v0.10.0-dev-1810+g16561dac3-Homebrew
Build type: Release
LuaJIT 2.1.1696795921

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-16561da/share/nvim"

Run :checkhealth for more info
```

For me, everything now works as expected. I'll close this issue.

**Comment by vitorf7** [comment]
Well funny enough this used to work for me using LazyVim and now no longer works again. When i run it nothing happens and if I try to run again it tells me that 'No tests found'
```
NVIM v0.10.0-dev-1376+geadedfd90
Build type: RelWithDebInfo
LuaJIT 2.1.1696795921
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/Users/vitorf7/code/personal/neovim/.deps/usr/include/luajit-2.1 -I/opt/homebrew/opt/gettext/include -I/Users/vitorf7/code/personal/neovim/.deps/usr/include -I/Users/vitorf7/code/personal/neovim/build/src/nvim/auto -I/Users/vitorf7/code/personal/neovim/build/include -I/Users/vitorf7/code/personal/neovim/build/cmake.config -I/Users/vitorf7/code/personal/neovim/src -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by nigelcss** [comment]
Also not working for me on LazyVim. I've also tried on the minimal config from OP and that's not working for me either.

I get the same 'No tests found' response, also the summary doesn't show individual test cases and running the whole file or module doesn't actually execute anything.

I've tested the same LazyVim config on rust and that's working fine.

```
NVIM v0.10.0-dev-1413+g684e93054-Homebrew
Build type: Release
LuaJIT 2.1.1696795921
Run "nvim -V1 -v" for more info
```

**Comment by nigelcss** [comment]
I did a fresh update this morning and everything is working perfectly again. There was a treesitter update, maybe in that. Anyways, all good and love your work.

**Comment by testinfected** [comment]
Sorry to reopen guys, but it still doesn't work for me on Neovim 0.9.4

No tests found and no test are shown in summary window, whatever I do

Tried `TSUninstall` and `TSInstall` without luck. Any clue?

Thanks

**Comment by dirodriguezm** [comment]
Hello, I'm sorry to comment again, but after reading all comments, I'm thinking this is related to Treesitter updates and it has stopped working recently.

It works if I run tests for the whole module, but for individual test I get "No tests found".

**Comment by tnthi115** [comment]
I'm also experiencing the same thing. I'm on neovim `v0.10.0` release and have reinstalled go treesitter parsers.
